In [1]:
import torch

x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5,3, requires_grad=True)
b = torch.randn(3, requires_grad = True)
z = torch.matmul(x,w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y)

In [2]:
x

tensor([1., 1., 1., 1., 1.])

In [3]:
w

tensor([[-0.8699,  0.2030, -0.8496],
        [-3.3721,  0.8853, -0.3926],
        [-1.1889,  0.9650, -0.4022],
        [-0.9620,  0.3341,  0.1824],
        [ 0.6691, -0.0370,  0.6146]], requires_grad=True)

In [4]:
print(torch.matmul(x,w))

tensor([-5.7238,  2.3503, -0.8474], grad_fn=<SqueezeBackward3>)


In [5]:
b

tensor([-1.5466, -0.5607,  1.2061], requires_grad=True)

In [6]:
z

tensor([-7.2704,  1.7896,  0.3587], grad_fn=<AddBackward0>)

In [7]:
y

tensor([0., 0., 0.])

In [8]:
print(loss)

tensor(0.9444, grad_fn=<BinaryCrossEntropyWithLogitsBackward>)


# What are the meaning of those above things

<br/>

<br/>

<br/>

<br/>



![](https://tutorials.pytorch.kr/_images/comp-graph.png)

In [9]:
print('Gradient function for z =', z.grad_fn)
print('Gradient function for loss =', loss.grad_fn)

Gradient function for z = <AddBackward0 object at 0x00000206386E6A00>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward object at 0x00000206386E6790>


In [10]:
loss.backward()

In [11]:
print(w.grad)
print(b.grad)

tensor([[2.3178e-04, 2.8563e-01, 1.9624e-01],
        [2.3178e-04, 2.8563e-01, 1.9624e-01],
        [2.3178e-04, 2.8563e-01, 1.9624e-01],
        [2.3178e-04, 2.8563e-01, 1.9624e-01],
        [2.3178e-04, 2.8563e-01, 1.9624e-01]])
tensor([2.3178e-04, 2.8563e-01, 1.9624e-01])


In [33]:
inp = torch.eye(5, requires_grad=True)
print(inp)
out = (inp+1).pow(2)
print("\n",out)
out.backward(torch.ones_like(inp), retain_graph=True)
print("\nFirst call\n", inp.grad)
out.backward(torch.ones_like(inp), retain_graph=True)
print("\nSecond call\n", inp.grad)
inp.grad.zero_()
out.backward(torch.ones_like(inp), retain_graph=True)
print("\nCall after zeroing gradients\n", inp.grad)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], requires_grad=True)

 tensor([[4., 1., 1., 1., 1.],
        [1., 4., 1., 1., 1.],
        [1., 1., 4., 1., 1.],
        [1., 1., 1., 4., 1.],
        [1., 1., 1., 1., 4.]], grad_fn=<PowBackward0>)

First call
 tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])

Second call
 tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.],
        [4., 4., 4., 4., 8.]])

Call after zeroing gradients
 tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])
